### ISSUE TITLE
Data preparation and Training guide

### ISSUE THREAD

**Issue by jayes97** [aleflabo/PREGO#1]
can you share more details on how to train model? also on Data preparation.

**Comment by HouTong-s** [comment]
same concern

**Comment by Bouclas** [comment]
+1

**Comment by aleflabo** [comment]
Hi all,

We appreciate your interest in our work.
We regret not releasing a clean, definitive version of the PREGO code sooner. During this period, we have been busy working on the follow-up [TI-PREGO: Chain of Thought and In-Context Learning for Online Mistake Detection in PRocedural EGOcentric Videos](https://arxiv.org/abs/2411.02570). 

We are now fixing the repo to allow you to train and infer PREGO and TI-PREGO.

As you can see in the README, we've released the code for the step anticipation branch. We'll incorporate step recognition and data aggregation soon. We've also uploaded the features for the Assembly101-O and Epic-tent-O datasets [here](https://drive.google.com/drive/u/1/folders/1gcOIEXhwysCE2o8-5C4vQnTShJ7p3CKH).
